### ISSUE TITLE
Not an issue but please help

### ISSUE THREAD

**Issue by SleazyFFXI** [RaraProjects/rest#4]
Any way I can easily disable the custom Horizon clear mind values?

**Comment by RaraProjects** [comment]
Not currently. Do you need the retail values? If so, I could add a toggle setting. In the meantime you could go to the /resources/clear_mind.lua file and adjust the values for each job/level to match what you need.

**Comment by SleazyFFXI** [comment]
Retail values yes please and thanks for the reply!

**Comment by SleazyFFXI** [comment]
Not really sure what ones to change,  could shoot you a message on Discord if possible

**Comment by SleazyFFXI** [comment]
One last thing lol,   any way for it to detect ticks from like Dalmy,  Refresh and lets say RDM relic head?

**Comment by RaraProjects** [comment]
Regrettably, I don't have the bandwidth to integrate a toggle for retail at the moment, but If you go into /rest/resources/clear_mind.lua I've added some comments that have the retail values (based on the wiki). You'll need to re-download to see the change. Additionally, in /rest/hpmp/_hpmp.lua I added a comment for the retail INC_HMP (additional HMP gained per tick) value. You can change the horizon values to those retail values to bring it closer to retail. It still won't be be perfect because Horizon has some level 75 additional HMP traits and retail has some additional clear mind HMP for certain levels that I don't account for, but hopefully it should be closer.

Some context for the Dalmatica ticks: Horizon has an interesting server delay issue where the ticks aren't always on 20 or 10 seconds, so the addon actually triggers the tick (resetting the timer) when it picks up that MP has been gained. In order to prevent the various forms of auto-refresh from triggering a tick timer reset I had to make it so only MP amounts greater than or equal to the base HMP rate (12 on horizon / 10 on retail) would cause the tick reset. You could potentially turn this off by going into /rest/ticks.lua and turning `if (new_mp - MP.Current) > HPMP.Enum.BASE_HMP then` into `if (new_mp - MP.Current) > 0 then` on line 35. I wouldn't recommend this as I believe it would make your tick timer reset every few seconds though.

**Comment by SleazyFFXI** [comment]
Thanks for the reply and thanks for your time
